FROM oven/bun:latest

WORKDIR /app

# Installation des dépendances
COPY package.json ./
COPY bun.lock ./
RUN bun install

# Copie du code source
COPY . .

# Build de l'application
RUN bun run build

EXPOSE 3000

# Démarrage avec vite preview sur le port 3000
CMD ["bun", "run", "preview", "--port", "3000", "--host", "0.0.0.0"]
