FROM oven/bun:latest

WORKDIR /app

# Installation des dépendances
COPY package.json ./
COPY bun.lock ./
RUN bun install

# Copie du code source (sans volume monté)
COPY . .

EXPOSE 3000

# Démarrage avec vite dev
CMD ["bun", "run", "dev"]
