/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StocksRouteImport } from './routes/stocks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as MaterielRouteImport } from './routes/materiel'
import { Route as CoordinatorRouteImport } from './routes/coordinator'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiChatVerduraRouteImport } from './routes/api/chat/verdura'

const StocksRoute = StocksRouteImport.update({
  id: '/stocks',
  path: '/stocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterielRoute = MaterielRouteImport.update({
  id: '/materiel',
  path: '/materiel',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatorRoute = CoordinatorRouteImport.update({
  id: '/coordinator',
  path: '/coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatVerduraRoute = ApiChatVerduraRouteImport.update({
  id: '/api/chat/verdura',
  path: '/api/chat/verdura',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/auth': typeof AuthRouteWithChildren
  '/carte': typeof CarteRoute
  '/coordinator': typeof CoordinatorRoute
  '/materiel': typeof MaterielRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/chat/verdura': typeof ApiChatVerduraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/auth': typeof AuthRouteWithChildren
  '/carte': typeof CarteRoute
  '/coordinator': typeof CoordinatorRoute
  '/materiel': typeof MaterielRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/chat/verdura': typeof ApiChatVerduraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/auth': typeof AuthRouteWithChildren
  '/carte': typeof CarteRoute
  '/coordinator': typeof CoordinatorRoute
  '/materiel': typeof MaterielRoute
  '/planning': typeof PlanningRoute
  '/settings': typeof SettingsRoute
  '/stocks': typeof StocksRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/chat/verdura': typeof ApiChatVerduraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/auth'
    | '/carte'
    | '/coordinator'
    | '/materiel'
    | '/planning'
    | '/settings'
    | '/stocks'
    | '/auth/callback'
    | '/api/chat/verdura'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/auth'
    | '/carte'
    | '/coordinator'
    | '/materiel'
    | '/planning'
    | '/settings'
    | '/stocks'
    | '/auth/callback'
    | '/api/chat/verdura'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/auth'
    | '/carte'
    | '/coordinator'
    | '/materiel'
    | '/planning'
    | '/settings'
    | '/stocks'
    | '/auth/callback'
    | '/api/chat/verdura'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnomaliesRoute: typeof AnomaliesRoute
  AuthRoute: typeof AuthRouteWithChildren
  CarteRoute: typeof CarteRoute
  CoordinatorRoute: typeof CoordinatorRoute
  MaterielRoute: typeof MaterielRoute
  PlanningRoute: typeof PlanningRoute
  SettingsRoute: typeof SettingsRoute
  StocksRoute: typeof StocksRoute
  ApiChatVerduraRoute: typeof ApiChatVerduraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stocks': {
      id: '/stocks'
      path: '/stocks'
      fullPath: '/stocks'
      preLoaderRoute: typeof StocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materiel': {
      id: '/materiel'
      path: '/materiel'
      fullPath: '/materiel'
      preLoaderRoute: typeof MaterielRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinator': {
      id: '/coordinator'
      path: '/coordinator'
      fullPath: '/coordinator'
      preLoaderRoute: typeof CoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat/verdura': {
      id: '/api/chat/verdura'
      path: '/api/chat/verdura'
      fullPath: '/api/chat/verdura'
      preLoaderRoute: typeof ApiChatVerduraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnomaliesRoute: AnomaliesRoute,
  AuthRoute: AuthRouteWithChildren,
  CarteRoute: CarteRoute,
  CoordinatorRoute: CoordinatorRoute,
  MaterielRoute: MaterielRoute,
  PlanningRoute: PlanningRoute,
  SettingsRoute: SettingsRoute,
  StocksRoute: StocksRoute,
  ApiChatVerduraRoute: ApiChatVerduraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
